DROP TABLE IF EXISTS invitee;
DROP TABLE IF EXISTS past_invitee;

CREATE TABLE invitee (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  attending BOOLEAN CHECK (attending IN (0, 1, 2))
);

CREATE TABLE past_invitee (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);
